// Generated by gencpp from file mavros_msgs/PolyWaypointAdd.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_POLYWAYPOINTADD_H
#define MAVROS_MSGS_MESSAGE_POLYWAYPOINTADD_H

#include <ros/service_traits.h>


#include <mavros_msgs/PolyWaypointAddRequest.h>
#include <mavros_msgs/PolyWaypointAddResponse.h>


namespace mavros_msgs
{

struct PolyWaypointAdd
{

typedef PolyWaypointAddRequest Request;
typedef PolyWaypointAddResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PolyWaypointAdd
} // namespace mavros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mavros_msgs::PolyWaypointAdd > {
  static const char* value()
  {
    return "cdf33b32ca0c3598cf8b0af6afe3f7af";
  }

  static const char* value(const ::mavros_msgs::PolyWaypointAdd&) { return value(); }
};

template<>
struct DataType< ::mavros_msgs::PolyWaypointAdd > {
  static const char* value()
  {
    return "mavros_msgs/PolyWaypointAdd";
  }

  static const char* value(const ::mavros_msgs::PolyWaypointAdd&) { return value(); }
};


// service_traits::MD5Sum< ::mavros_msgs::PolyWaypointAddRequest> should match 
// service_traits::MD5Sum< ::mavros_msgs::PolyWaypointAdd > 
template<>
struct MD5Sum< ::mavros_msgs::PolyWaypointAddRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mavros_msgs::PolyWaypointAdd >::value();
  }
  static const char* value(const ::mavros_msgs::PolyWaypointAddRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros_msgs::PolyWaypointAddRequest> should match 
// service_traits::DataType< ::mavros_msgs::PolyWaypointAdd > 
template<>
struct DataType< ::mavros_msgs::PolyWaypointAddRequest>
{
  static const char* value()
  {
    return DataType< ::mavros_msgs::PolyWaypointAdd >::value();
  }
  static const char* value(const ::mavros_msgs::PolyWaypointAddRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mavros_msgs::PolyWaypointAddResponse> should match 
// service_traits::MD5Sum< ::mavros_msgs::PolyWaypointAdd > 
template<>
struct MD5Sum< ::mavros_msgs::PolyWaypointAddResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mavros_msgs::PolyWaypointAdd >::value();
  }
  static const char* value(const ::mavros_msgs::PolyWaypointAddResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros_msgs::PolyWaypointAddResponse> should match 
// service_traits::DataType< ::mavros_msgs::PolyWaypointAdd > 
template<>
struct DataType< ::mavros_msgs::PolyWaypointAddResponse>
{
  static const char* value()
  {
    return DataType< ::mavros_msgs::PolyWaypointAdd >::value();
  }
  static const char* value(const ::mavros_msgs::PolyWaypointAddResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAVROS_MSGS_MESSAGE_POLYWAYPOINTADD_H
