// Generated by gencpp from file mavros_msgs/PolyStop.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_POLYSTOP_H
#define MAVROS_MSGS_MESSAGE_POLYSTOP_H

#include <ros/service_traits.h>


#include <mavros_msgs/PolyStopRequest.h>
#include <mavros_msgs/PolyStopResponse.h>


namespace mavros_msgs
{

struct PolyStop
{

typedef PolyStopRequest Request;
typedef PolyStopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PolyStop
} // namespace mavros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mavros_msgs::PolyStop > {
  static const char* value()
  {
    return "b2e171e32daca896a60ae860b3386531";
  }

  static const char* value(const ::mavros_msgs::PolyStop&) { return value(); }
};

template<>
struct DataType< ::mavros_msgs::PolyStop > {
  static const char* value()
  {
    return "mavros_msgs/PolyStop";
  }

  static const char* value(const ::mavros_msgs::PolyStop&) { return value(); }
};


// service_traits::MD5Sum< ::mavros_msgs::PolyStopRequest> should match 
// service_traits::MD5Sum< ::mavros_msgs::PolyStop > 
template<>
struct MD5Sum< ::mavros_msgs::PolyStopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mavros_msgs::PolyStop >::value();
  }
  static const char* value(const ::mavros_msgs::PolyStopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros_msgs::PolyStopRequest> should match 
// service_traits::DataType< ::mavros_msgs::PolyStop > 
template<>
struct DataType< ::mavros_msgs::PolyStopRequest>
{
  static const char* value()
  {
    return DataType< ::mavros_msgs::PolyStop >::value();
  }
  static const char* value(const ::mavros_msgs::PolyStopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mavros_msgs::PolyStopResponse> should match 
// service_traits::MD5Sum< ::mavros_msgs::PolyStop > 
template<>
struct MD5Sum< ::mavros_msgs::PolyStopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mavros_msgs::PolyStop >::value();
  }
  static const char* value(const ::mavros_msgs::PolyStopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mavros_msgs::PolyStopResponse> should match 
// service_traits::DataType< ::mavros_msgs::PolyStop > 
template<>
struct DataType< ::mavros_msgs::PolyStopResponse>
{
  static const char* value()
  {
    return DataType< ::mavros_msgs::PolyStop >::value();
  }
  static const char* value(const ::mavros_msgs::PolyStopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAVROS_MSGS_MESSAGE_POLYSTOP_H
