set(_CATKIN_CURRENT_PACKAGE "multirotor_test")
set(multirotor_test_VERSION "0.0.0")
set(multirotor_test_MAINTAINER "lbf10 <leonardo.farconi@gmail.com>")
set(multirotor_test_PACKAGE_FORMAT "2")
set(multirotor_test_BUILD_DEPENDS "geometry_msgs" "mavros_msgs" "message_generation" "nav_msgs" "roscpp" "rospy" "std_msgs")
set(multirotor_test_BUILD_EXPORT_DEPENDS "geometry_msgs" "mavros_msgs" "nav_msgs" "roscpp" "rospy" "std_msgs")
set(multirotor_test_BUILDTOOL_DEPENDS "catkin" "genmsg")
set(multirotor_test_BUILDTOOL_EXPORT_DEPENDS )
set(multirotor_test_EXEC_DEPENDS "geometry_msgs" "mavros_msgs" "nav_msgs" "roscpp" "rospy" "std_msgs" "message_runtime")
set(multirotor_test_RUN_DEPENDS "geometry_msgs" "mavros_msgs" "nav_msgs" "roscpp" "rospy" "std_msgs" "message_runtime")
set(multirotor_test_TEST_DEPENDS )
set(multirotor_test_DOC_DEPENDS )
set(multirotor_test_URL_WEBSITE "")
set(multirotor_test_URL_BUGTRACKER "")
set(multirotor_test_URL_REPOSITORY "")
set(multirotor_test_DEPRECATED "")